name: WaterFix
version: @VERSION@
description: Create water when at least two sources are supplying to same block
author: EdGruberman (ed@rjump.com)
website: http://github.com/EdGruberman/WaterFix
main: edgruberman.bukkit.waterfix.Main